# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d34c5fd8806ce398f9a4f0a3651e675c262cb907eca96089c06313e58319d06c14a750c4a7079831501099809992b693e40a6a476af12285849bd623097faf3

test:
  secret_key_base: 82c48352370ce65a3c4ae50437df8de98453178f4d98765e21090a914c0f9ce9c9da712211cee317eec45a6f36adf694d3697a6e4e2a7b9857b87d218f19e82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
